export const demoArchive = {
  version: 1,
  books: [
    {
      id: "book_001",
      title: "看不见的城市",
      subtitle: "城市与记忆的五十五种方式",
      author: "伊塔洛·卡尔维诺",
      publisher: "译林出版社",
      status: "finished",
      progress: 100,
      rating: 5,
      startedAt: "2026-03-12",
      finishedAt: "2026-03-28",
      lastReadAt: "2026-03-28",
      tags: ["城市", "记忆", "文学"],
      summary: "它并不回答城市是什么，而是不断改变我观看城市的角度。最重要的不是奇观，而是记忆如何替空间重新命名。",
      coverTone: 0
    },
    {
      id: "book_002",
      title: "论摄影",
      subtitle: "观看、占有与记忆",
      author: "苏珊·桑塔格",
      publisher: "上海译文出版社",
      status: "reading",
      progress: 62,
      rating: 0,
      startedAt: "2026-08-09",
      finishedAt: "",
      lastReadAt: "2026-08-28",
      tags: ["摄影", "观看", "媒介"],
      summary: "正在重新理解拍照这件日常动作：它既保存经验，也可能让经验变得可消费。",
      coverTone: 1
    },
    {
      id: "book_003",
      title: "始于极限",
      subtitle: "女性主义往复书简",
      author: "上野千鹤子、铃木凉美",
      publisher: "新星出版社",
      status: "finished",
      progress: 100,
      rating: 4,
      startedAt: "2025-11-02",
      finishedAt: "2025-11-20",
      lastReadAt: "2025-11-20",
      tags: ["女性主义", "关系", "社会"],
      summary: "两代女性经验之间不是整齐的传承，而是带着冒犯、误解与重新理解的往复。",
      coverTone: 2
    },
    {
      id: "book_004",
      title: "一间自己的房间",
      subtitle: "",
      author: "弗吉尼亚·伍尔夫",
      publisher: "人民文学出版社",
      status: "wishlist",
      progress: 0,
      rating: 0,
      startedAt: "",
      finishedAt: "",
      lastReadAt: "",
      tags: ["女性主义", "写作"],
      summary: "待读：与《始于极限》一起回看女性、写作与经济独立。",
      coverTone: 3
    }
  ],
  annotations: [
    {
      id: "ann_001",
      bookId: "book_001",
      chapter: "城市与记忆·之三",
      originalText: "记忆中的形象一旦固定下来，语言便将它们抹去。",
      comment: "记录不必然抵抗遗忘；有时格式化的记录本身就在替换原来的感受。",
      type: "comment",
      sourceCreatedAt: "2026-03-18",
      importedAt: "2026-03-29T08:20:00.000Z",
      tags: ["记忆", "记录"],
      organized: true,
      contentHash: "145pbtw"
    },
    {
      id: "ann_002",
      bookId: "book_001",
      chapter: "城市与欲望·之二",
      originalText: "你喜爱的不是一座城市的七个或七十个奇迹，而是它对你的一个问题所给予的回答。",
      comment: "也许旅行真正留下的是我们当时向世界提出了什么问题。",
      type: "comment",
      sourceCreatedAt: "2026-03-22",
      importedAt: "2026-03-29T08:20:00.000Z",
      tags: ["城市", "旅行"],
      organized: false,
      contentHash: "huxzhi"
    },
    {
      id: "ann_003",
      bookId: "book_002",
      chapter: "在柏拉图的洞穴里",
      originalText: "收藏照片就是收藏世界。",
      comment: "为什么手机相册越多，真正能够复述的生活反而越少？",
      type: "comment",
      sourceCreatedAt: "2026-08-11",
      importedAt: "2026-08-29T09:00:00.000Z",
      tags: ["摄影", "占有"],
      organized: false,
      contentHash: "ewlqrp"
    },
    {
      id: "ann_004",
      bookId: "book_002",
      chapter: "透过照片看美国，昏暗地",
      originalText: "相机使现实成为原子的、易于处理的和不透明的。",
      comment: "",
      type: "highlight",
      sourceCreatedAt: "2026-08-24",
      importedAt: "2026-08-29T09:00:00.000Z",
      tags: [],
      organized: false,
      contentHash: "134oop"
    },
    {
      id: "ann_005",
      bookId: "book_003",
      chapter: "母女",
      originalText: "理解并不意味着同意，它只是让分歧变得更具体。",
      comment: "这句话可以用来重新看待很多代际争论。",
      type: "comment",
      sourceCreatedAt: "2025-11-12",
      importedAt: "2025-11-21T12:00:00.000Z",
      tags: ["代际", "分歧"],
      organized: true,
      contentHash: "1po9nfa"
    }
  ],
  reflections: []
};
